name: game
description: Simple sports game.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.3.0
  flame_forge2d: ^0.12.2
  flame_tiled: ^1.7.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/court.svg
    - assets/images/basket.svg
    - assets/images/blue_player_sprite.png
    - assets/images/red_player_sprite.png
    - assets/images/bouncing_ball_sprite.png
    - assets/images/spinning_ball_sprite.png
